// Package hive_metastore provides raw access to HMS Thrift API.
// It is auto-generated by thrift compiler using the following command:
//    thrift -v -r --gen go hive_metastore.thrift
package hive_metastore
